//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MathIsCool.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class math_is_coolEntities2 : DbContext
    {
        public math_is_coolEntities2()
            : base("name=math_is_coolEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<address> addresses { get; set; }
        public virtual DbSet<calendar> calendars { get; set; }
        public virtual DbSet<comp_location> comp_location { get; set; }
        public virtual DbSet<competition> competitions { get; set; }
        public virtual DbSet<faq> faqs { get; set; }
        public virtual DbSet<invoice> invoices { get; set; }
        public virtual DbSet<line_item> line_item { get; set; }
        public virtual DbSet<permission> permissions { get; set; }
        public virtual DbSet<region> regions { get; set; }
        public virtual DbSet<registration> registrations { get; set; }
        public virtual DbSet<sample> samples { get; set; }
        public virtual DbSet<school> schools { get; set; }
        public virtual DbSet<sku> skus { get; set; }
        public virtual DbSet<student> students { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
